import React from 'react';
import imgUrl from 'src/assets/img/beams-basic.png';

const Disclaimer = () => {
  return (
    <div className="relative -mt-[5.75rem] overflow-hidden pt-[5.75rem]">
      <img
        src={imgUrl}
        alt=""
        className="absolute left-1/2 top-0 -ml-[39rem] w-[113.125rem] max-w-none"
        data-xblocker="passed"
        style={{ visibility: 'visible' }}
      />
      <div className="px-4 sm:px-6 lg:px-8">
        <div className="relative mx-auto max-w-[37.5rem] pt-20 text-center pb-24">
          <h1 className="text-4xl font-extrabold tracking-tight text-slate-900 sm:text-5xl">
            Disclaimer
          </h1>
          <p className="mt-4 text-base leading-7 text-slate-600">
            Last updated: May 4, 2023
          </p>
        </div>
      </div>
      <div className="relative px-4 pb-20 sm:px-6 lg:px-8">
        <div className="mx-auto max-w-[50rem] prose-xl prose prose-slate prose-a:font-semibold prose-a:text-sky-500 hover:prose-a:text-sky-600">
          <p>
            Please read this disclaimer carefully before using the Case Cruncher
            website ("Website") operated by Case Cruncher, Inc. ("us", "we", or
            "our").
          </p>
          <h2>Use of the Website</h2>
          <p>
            By accessing and using the Website, you acknowledge that you have
            read, understood, and agree to be bound by the terms and conditions
            of this disclaimer. If you do not agree with any part of this
            disclaimer, you must not use the Website.
          </p>
          <h2>Purpose of the Website</h2>
          <p>
            The purpose of the Website is to provide a tool that uses Artificial
            Intelligence (AI) to help users reduce reading time and improve
            their understanding of the content being reviewed. The AI generates
            data and suggestions based on the user's preferences and the
            information provided.
          </p>
          <h2>User Responsibility</h2>
          <p>
            You, as the user, are solely responsible for reviewing and
            interpreting the data generated by the AI on the Website. While Case
            Cruncher aims to provide accurate and useful information, we cannot
            guarantee the correctness, completeness, or suitability of the data
            generated by the AI. The Website is meant to assist you in your
            research and analysis, but it should not be considered as a
            substitute for your own judgment or professional advice.
          </p>
          <p>
            By using the Website, you agree that you are 100% responsible for
            reviewing, accepting, or rejecting the AI-generated data. You
            acknowledge that you will exercise due diligence and verify the
            accuracy and reliability of the information provided by the AI
            before relying on it for any decision-making purpose.
          </p>
          <h2>Limitation of Liability</h2>
          <p>
            In no event shall Case Cruncher, its officers, directors, employees,
            or affiliates be liable for any direct, indirect, incidental,
            special, consequential, or punitive damages, including but not
            limited to, loss of profits, data, or use, arising out of or in
            connection with your use of the Website or reliance on the
            AI-generated data, whether based on warranty, contract, tort, or any
            other legal theory, and whether or not we have been advised of the
            possibility of such damages.
          </p>
          <h2>Indemnification</h2>
          <p>
            You agree to defend, indemnify, and hold harmless Case Cruncher, its
            officers, directors, employees, and affiliates from and against any
            and all claims, damages, obligations, losses, liabilities, costs,
            and expenses (including but not limited to attorney's fees) arising
            from your use of the Website, your violation of any term of this
            disclaimer, or your infringement of any third party's rights.
          </p>
          <h2>Changes to This Disclaimer</h2>
          <p>
            We may update this disclaimer from time to time. We will notify you
            of any changes by posting the new disclaimer on this page. You are
            advised to review this disclaimer periodically for any changes.
          </p>
          <h2>Contacting us</h2>
          <p>
            If you have any questions or concerns about this disclaimer, please
            contact us at:
          </p>
          <p>Case Cruncher</p>
          <p>
            Email:{' '}
            <a href="mailto:support@tailwindui.com">support@tailwindui.com</a>
          </p>
        </div>
      </div>
    </div>
  );
};

export default Disclaimer;
